staticfiles_urls = {
    'blueimp/css/blueimp-gallery-indicator.css': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/css/blueimp-gallery-indicator.css',  # NOQA
    'blueimp/css/blueimp-gallery-video.css': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/css/blueimp-gallery-video.css',  # NOQA
    'blueimp/css/blueimp-gallery.css': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/css/blueimp-gallery.css',  # NOQA
    'blueimp/css/blueimp-gallery.min.css': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/css/blueimp-gallery.min.css',  # NOQA
    'blueimp/css/blueimp-gallery.min.css.map': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/css/blueimp-gallery.min.css.map',  # NOQA
    'blueimp/img/error.png': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/error.png',  # NOQA
    'blueimp/img/error.svg': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/error.svg',  # NOQA
    'blueimp/img/loading.gif': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/loading.gif',  # NOQA
    'blueimp/img/play-pause.png': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/play-pause.png',  # NOQA
    'blueimp/img/play-pause.svg': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/play-pause.svg',  # NOQA
    'blueimp/img/video-play.png': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/video-play.png',  # NOQA
    'blueimp/img/video-play.svg': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/img/video-play.svg',  # NOQA
    'blueimp/js/blueimp-gallery-fullscreen.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery-fullscreen.js',  # NOQA
    'blueimp/js/blueimp-gallery-indicator.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery-indicator.js',  # NOQA
    'blueimp/js/blueimp-gallery-video.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery-video.js',  # NOQA
    'blueimp/js/blueimp-gallery-vimeo.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery-vimeo.js',  # NOQA
    'blueimp/js/blueimp-gallery-youtube.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery-youtube.js',  # NOQA
    'blueimp/js/blueimp-gallery.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery.js',  # NOQA
    'blueimp/js/blueimp-gallery.min.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery.min.js',  # NOQA
    'blueimp/js/blueimp-gallery.min.js.map': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-gallery.min.js.map',  # NOQA
    'blueimp/js/blueimp-helper.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/blueimp-helper.js',  # NOQA
    'blueimp/js/jquery.blueimp-gallery.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/jquery.blueimp-gallery.js',  # NOQA
    'blueimp/js/jquery.blueimp-gallery.min.js': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/jquery.blueimp-gallery.min.js',  # NOQA
    'blueimp/js/jquery.blueimp-gallery.min.js.map': 'https://raw.githubusercontent.com/blueimp/Gallery/v2.27.0/js/jquery.blueimp-gallery.min.js.map',  # NOQA
    'bootstrap/css/bootstrap-theme.css': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.css',  # NOQA
    'bootstrap/css/bootstrap.min.css': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css',  # NOQA
    'bootstrap/css/bootstrap-theme.css.map': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.css.map',  # NOQA
    'bootstrap/css/bootstrap.min.css.map': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css.map',  # NOQA
    'bootstrap/css/bootstrap-theme.min.css': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css',  # NOQA
    'bootstrap/css/bootstrap.css': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css',  # NOQA
    'bootstrap/css/bootstrap-theme.min.css.map': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css.map',  # NOQA
    'bootstrap/css/bootstrap.css.map': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css.map',  # NOQA
    'bootstrap/fonts/glyphicons-halflings-regular.svg': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/fonts/glyphicons-halflings-regular.svg',  # NOQA
    'bootstrap/fonts/glyphicons-halflings-regular.ttf': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/fonts/glyphicons-halflings-regular.ttf',  # NOQA
    'bootstrap/fonts/glyphicons-halflings-regular.eot': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/fonts/glyphicons-halflings-regular.eot',  # NOQA
    'bootstrap/fonts/glyphicons-halflings-regular.woff': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff',  # NOQA
    'bootstrap/fonts/glyphicons-halflings-regular.woff2': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff2',  # NOQA
    'bootstrap/js/bootstrap.min.js': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js',  # NOQA
    'bootstrap/js/npm.js': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/npm.js',  # NOQA
    'bootstrap/js/bootstrap.js': 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js',  # NOQA
    'jquery/jquery-3.2.1.js': 'https://code.jquery.com/jquery-3.2.1.js',  # NOQA
    'jquery/jquery-3.2.1.min.js': 'https://code.jquery.com/jquery-3.2.1.min.js',  # NOQA
    'jquery/jquery-3.2.1.min.map': 'https://code.jquery.com/jquery-3.2.1.min.map',  # NOQA
}
